// Generated by CoffeeScript 1.4.0
(function() {
  var Asset, BSON, mongo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  mongo = require('mongodb');

  BSON = mongo.BSONPure;

  Asset = {};

  Asset = (function() {

    function Asset(opts, db) {
      this.url = __bind(this.url, this);
      this.Asset = this;
      this.db = db;
      this.host = opts.asset_host;
      this.port = opts.asset_port;
      this.asset_servers = opts.asset_servers;
    }

    Asset.prototype.url = function(asset_id, file_name, callback) {
      var _this = this;
      return this._findAsset(asset_id, function(record) {
        var storage, url;
        if (!record) {
          return callback("http://google.com");
        }
        storage = _this.asset_servers[record["storage"]] || _this.asset_servers["cdn"];
        if (record["storage"] == null) {
          url = "http://" + storage['host'] + ":" + storage['port'] + "/uploads/asset/image/" + asset_id + "/" + file_name;
        } else {
          url = "http://" + storage['host'] + ":" + storage['port'] + "/uploads/" + asset_id + "/" + file_name;
        }
        return callback(url);
      });
    };

    Asset.prototype._findAsset = function(asset_id, callback) {
      var o_id,
        _this = this;
      o_id = new BSON.ObjectID(asset_id);
      return this.db.collection("assets", function(dbErr, collection) {
        return collection.find({
          _id: o_id
        }).nextObject(function(err, result) {
          if (err == null) {
            callback(result);
          }
          return _this.db.close();
        });
      });
    };

    return Asset;

  })();

  exports.Asset = Asset;

}).call(this);
